puphpet.extension.memcache.homepage:
    pattern:  /
    defaults: { _controller: PuphpetExtensionMemcacheBundle:Front:index }

puphpet.extension.memcache.manifest:
    pattern:  /manifest
    defaults: { _controller: PuphpetExtensionMemcacheBundle:Manifest:index }
